print("Welcome to the tip caclculator!")
total = float(input("What was the total bill? $"))
percentage = int(input("How much tip would you like to give? 10. 12. or 15? "))
split = int(input("How many people to split the bill? "))
print(f"Each person should pay: ${round(((total * (100 + percentage) / 100) / split), 2)}")